# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Share' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  #snapkit
  pod 'SnapKit', '~> 5.7.0'
  # Pods for Share
  
  # To recognize Latin script
  pod 'GoogleMLKit/TextRecognition', '3.2.0'

  # To recognize Korean script
  pod 'GoogleMLKit/TextRecognitionKorean', '3.2.0'
  
  # OCR, AI 생성된 일정 저장 관리를 위한 DB
  pod 'RealmSwift', '~>10'
  
  

end

target 'SyncReady' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SyncReady
  
# To recognize Latin script
pod 'GoogleMLKit/TextRecognition', '3.2.0'

# To recognize Korean script
pod 'GoogleMLKit/TextRecognitionKorean', '3.2.0'

# OCR, AI 생성된 일정 저장 관리를 위한 DB
pod 'RealmSwift', '~>10'

end
