# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Share' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  #snapkit
  pod 'SnapKit', '~> 5.7.0'
  # Pods for Share

end

target 'SyncReady' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SyncReady

# To recognize Korean script
pod 'GoogleMLKit/TextRecognitionKorean', '3.2.0'

end
